[project]
name = "ssi-backend"
version = "0.1.0"
description = "The Backend of the Service Status Indicator monitoring framework"
authors = [
    {name = "RemiZlatinis",email = "remizlatinis@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=5.2.6,<6.0.0)"
]

[tool.poetry]
package-mode = false
packages = [{include = "project"}]

[tool.poetry.scripts]
runserver = "manage:main runserver"
migrate = "manage:main migrate"
makemigrations = "manage:main makemigrations"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
